In [4]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('ai_job_market_insights.csv')

# Mapping dictionaries
ai_adoption_mapping = {'Low': 1, 'Medium': 2, 'High': 3}
automation_risk_mapping = {'Low': 1, 'Medium': 2, 'High': 3}
remote_friendly_mapping = {'Yes': 1, 'No': 0}
job_growth_mapping = {'Growth': 1, 'Decline': -1, 'Stable': 0}
# Applying the mappings to the respective columns
data['AI_Adoption_Level'] = data['AI_Adoption_Level'].map(ai_adoption_mapping)
data['Automation_Risk'] = data['Automation_Risk'].map(automation_risk_mapping)
data['Remote_Friendly'] = data['Remote_Friendly'].map(remote_friendly_mapping)
data['Job_Growth_Projection'] = data['Job_Growth_Projection'].map(job_growth_mapping)

# Display the updated dataset to check if the changes were applied correctly
data.head()

,Job_Title,Industry,Company_Size,Location,AI_Adoption_Level,Automation_Risk,Required_Skills,Salary_USD,Remote_Friendly,Job_Growth_Projection
0,Cybersecurity Analyst,Entertainment,Small,Dubai,2,3,UX/UI Design,111392.165243,1,1
1,Marketing Specialist,Technology,Large,Singapore,2,3,Marketing,93792.562466,0,-1
2,AI Researcher,Technology,Large,Singapore,2,3,UX/UI Design,107170.263069,1,1
3,Sales Manager,Retail,Small,Berlin,1,3,Project Management,93027.953758,0,1
4,Cybersecurity Analyst,Entertainment,Small,Tokyo,1,1,JavaScript,87752.922171,1,-1

In [5]:
output_file_path = '/Users/zhanyijun/Desktop/24Fall/NextGen-Jobs/processed_ai_job_market_insights.csv'
data.to_csv(output_file_path, index=False)

In [1]:
import pandas as pd

# Load CSV file
job_data = pd.read_csv('ai_job_market_insights.csv')

# Extract unique city names
unique_cities = job_data['Location'].unique()
print(unique_cities)

['Dubai' 'Singapore' 'Berlin' 'Tokyo' 'San Francisco' 'London' 'Paris'
 'Sydney' 'New York' 'Toronto']